# Application Name
spring.application.name=erp_solution
server.port=8443

# HTTPS/SSL Configuration
#server.ssl.enabled=true
#server.ssl.key-store=/home/fuma/ssl-backend/backend.p12
#server.ssl.key-store-password=fuma@01234
#server.ssl.key-store-type=PKCS12
#server.ssl.key-alias=backend
# Database Configuration
spring.datasource.url=jdbc:mysql://162.240.158.75:3306/fuma_fumamain?serverTimezone=Asia/Kolkata
spring.datasource.username=fuma_dbuser
spring.datasource.password=Fuma@01234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-init-sql=SET time_zone = '+05:30'

# Ensure Jackson serializes dates as ISO strings
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata
       
# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Session Timeout
server.servlet.session.timeout=10m

# File Upload Settings
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# File Upload Directory
file.upload-dir=D:/erp/erp_solution/uploads/

# Static Resource Mapping
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=file:D:/erp/erp_solution/uploads/

# HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
